import Providers from "@vape/components/core/Providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="fr">
            <body className={inter.className} suppressHydrationWarning={true}>
                <NextTopLoader color="#73CA16" showSpinner={false} />

                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
